# Generated by Django 6.0.8 on 2026-08-04 20:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. HDFC Bank, SBI Savings, Cash Wallet, Zerodha Demat",
                        max_length=100,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Account"),
                            ("CASH", "Cash Wallet"),
                            ("WALLET", "Digital Wallet / UPI"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEMAT", "Demat / Investment Account"),
                        ],
                        default="BANK",
                        max_length=20,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank or Broker name e.g. ICICI, Zerodha, Paytm",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "account_number_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits or card number",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current liquid balance or available cash",
                        max_digits=14,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum total limit (for credit cards)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "card_due_date",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month when bill is due (1-31)",
                        null=True,
                    ),
                ),
                (
                    "invested_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total active capital invested (for Demat)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#6366f1",
                        help_text="Accent theme color for UI card display",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-wallet",
                        help_text="FontAwesome icon class (e.g. fa-university, fa-credit-card, fa-chart-line)",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE", "Expense"),
                            ("INCOME", "Income"),
                            ("TRANSFER", "Internal Self Transfer"),
                            ("PAY_PEOPLE", "Paid to Person / External"),
                            ("CARD_PAYMENT", "Credit Card Bill Payment"),
                            ("DEMAT_DEPOSIT", "Investment into Demat"),
                            ("DEMAT_WITHDRAWAL", "Withdrawal from Demat"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food & Dining"),
                            ("SHOPPING", "Shopping & Electronics"),
                            ("BILLS", "Utilities & Bills"),
                            ("SALARY", "Salary & Income"),
                            ("RENT", "Rent & Housing"),
                            ("INVESTMENT", "Investments & Mutual Funds"),
                            ("TRANSFER", "Account Transfer"),
                            ("CARD_BILL", "Credit Card Bill"),
                            ("ENTERTAINMENT", "Entertainment & Subscriptions"),
                            ("OTHERS", "Others / Misc"),
                        ],
                        default="OTHERS",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Person or Merchant name if paying externally",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Reason / Note for the transaction",
                        null=True,
                    ),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_transactions",
                        to="finance.account",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_transactions",
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
