# Generated by Django 6.0.8 on 2026-08-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_account_user_transaction_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.CharField(default="true", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
