# Generated by Django 6.0.8 on 2026-08-06 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_systemsetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=100)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("LENT", "Lent to Someone"),
                            ("BORROWED", "Borrowed from Someone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Notes about the debt", null=True
                    ),
                ),
                ("is_settled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food & Dining"),
                            ("SHOPPING", "Shopping & Electronics"),
                            ("BILLS", "Utilities & Bills"),
                            ("SALARY", "Salary & Income"),
                            ("RENT", "Rent & Housing"),
                            ("INVESTMENT", "Investments & Mutual Funds"),
                            ("TRANSFER", "Account Transfer"),
                            ("CARD_BILL", "Credit Card Bill"),
                            ("ENTERTAINMENT", "Entertainment & Subscriptions"),
                            ("OTHERS", "Others / Misc"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount_limit", models.DecimalField(decimal_places=2, max_digits=14)),
                ("month", models.IntegerField(help_text="Month number e.g. 8")),
                ("year", models.IntegerField(help_text="Year e.g. 2026")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "category", "month", "year")},
            },
        ),
    ]
