# Generated by Django 6.0.8 on 2026-08-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_debt_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked financial account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debts",
                to="finance.account",
            ),
        ),
    ]
