# Generated by Django 6.0.8 on 2026-08-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_debt_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="date",
            field=models.DateField(
                blank=True, help_text="Date when debt was incurred", null=True
            ),
        ),
    ]
