# Generated by Django 6.0.8 on 2026-08-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_debt_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Transaction Categories",
            },
        ),
    ]
