# Generated by Django 6.0.8 on 2026-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_transactioncategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("EXPENSE", "Expense"),
                    ("INCOME", "Income"),
                    ("TRANSFER", "Internal Self Transfer"),
                    ("PAY_PEOPLE", "Paid to Person / External"),
                    ("CARD_PAYMENT", "Credit Card Bill Payment"),
                    ("DEMAT_DEPOSIT", "Investment into Demat"),
                    ("DEMAT_WITHDRAWAL", "Withdrawal from Demat"),
                    ("BUY_PORTFOLIO", "Buy Portfolio / Invest Cash in Demat"),
                    ("SELL_PORTFOLIO", "Liquidate Portfolio to Demat Cash"),
                    ("DIRECT_INVEST", "Direct Investment from Bank to Demat Portfolio"),
                    ("PORTFOLIO_VALUATION", "Portfolio Valuation Adjustment"),
                ],
                max_length=20,
            ),
        ),
    ]
