# Generated by Django 6.0.8 on 2026-09-15 21:34

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_transaction_transaction_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="HistoricalAccount",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. HDFC Bank, SBI Savings, Cash Wallet, Zerodha Demat",
                        max_length=100,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Account"),
                            ("CASH", "Cash Wallet"),
                            ("WALLET", "Digital Wallet / UPI"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEMAT", "Demat / Investment Account"),
                        ],
                        default="BANK",
                        max_length=20,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank or Broker name e.g. ICICI, Zerodha, Paytm",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "account_number_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits or card number",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current liquid balance or available cash",
                        max_digits=14,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum total limit (for credit cards)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "card_due_date",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month when bill is due (1-31)",
                        null=True,
                    ),
                ),
                (
                    "invested_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total active capital invested (for Demat)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#6366f1",
                        help_text="Accent theme color for UI card display",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-wallet",
                        help_text="FontAwesome icon class (e.g. fa-university, fa-credit-card, fa-chart-line)",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical account",
                "verbose_name_plural": "historical accounts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBudget",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("amount_limit", models.DecimalField(decimal_places=2, max_digits=14)),
                ("month", models.IntegerField(help_text="Month number e.g. 8")),
                ("year", models.IntegerField(help_text="Year e.g. 2026")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical budget",
                "verbose_name_plural": "historical budgets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDebt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("person_name", models.CharField(max_length=100)),
                (
                    "debt_type",
                    models.CharField(
                        choices=[
                            ("LENT", "Lent to Someone"),
                            ("BORROWED", "Borrowed from Someone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date when debt was incurred", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Notes about the debt", null=True
                    ),
                ),
                ("is_settled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Linked financial account",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical debt",
                "verbose_name_plural": "historical debts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTransaction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("EXPENSE", "Expense"),
                            ("INCOME", "Income"),
                            ("TRANSFER", "Internal Self Transfer"),
                            ("PAY_PEOPLE", "Paid to Person / External"),
                            ("CARD_PAYMENT", "Credit Card Bill Payment"),
                            ("DEMAT_DEPOSIT", "Investment into Demat"),
                            ("DEMAT_WITHDRAWAL", "Withdrawal from Demat"),
                            ("BUY_PORTFOLIO", "Buy Portfolio / Invest Cash in Demat"),
                            ("SELL_PORTFOLIO", "Liquidate Portfolio to Demat Cash"),
                            (
                                "DIRECT_INVEST",
                                "Direct Investment from Bank to Demat Portfolio",
                            ),
                            ("PORTFOLIO_VALUATION", "Portfolio Valuation Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food & Dining"),
                            ("SHOPPING", "Shopping & Electronics"),
                            ("BILLS", "Utilities & Bills"),
                            ("SALARY", "Salary & Income"),
                            ("RENT", "Rent & Housing"),
                            ("INVESTMENT", "Investments & Mutual Funds"),
                            ("TRANSFER", "Account Transfer"),
                            ("CARD_BILL", "Credit Card Bill"),
                            ("ENTERTAINMENT", "Entertainment & Subscriptions"),
                            ("OTHERS", "Others / Misc"),
                        ],
                        default="OTHERS",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True,
                        help_text="Person or Merchant name if paying externally",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Reason / Note for the transaction",
                        null=True,
                    ),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical transaction",
                "verbose_name_plural": "historical transactions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTransactionCategory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical transaction category",
                "verbose_name_plural": "historical Transaction Categories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
